CREATE TABLE Users(
	ID INT PRIMARY KEY AUTO_INCREMENT,
    USERNAME VARCHAR(100) NOT NULL UNIQUE, 
    EMAIL VARCHAR(100) NOT NULL UNIQUE,
    PASSWORD VARCHAR(100) NOT NULL
);

SELECT * FROM Users;
SELECT USERNAME, PASSWORD FROM Users WHERE USERNAME = 'Alin';
DROP TABLE Users; 
SELECT USERNAME FROM Users WHERE USERNAME = 'Alin';
